# Generated by Django 3.0.7 on 2020-06-18 06:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Navnefeltet er påkrævet.'}, help_text='Et beskrivende navn til rollen.', max_length=255, unique=True)),
                ('display_name', models.CharField(error_messages={'required': 'Visningsnavnefeltet er påkrævet.'}, help_text='Navnet der bliver vist på siden.', max_length=255)),
                ('description', models.CharField(error_messages={'required': 'Beskrivelsesfeltet er påkrævet.'}, help_text='En lille beskrivelse af rollen.', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default=None, help_text='Et telefonnummer du kan kontaktes på.', max_length=8, null=True, validators=[django.core.validators.RegexValidator('[0-9]*', 'Dit telefonnummer kan kun indeholde tal.')])),
                ('pfp', models.ImageField(default='img/default.jpg', upload_to='img/pfp/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, default=None, help_text="Brugerens rolle. Denne vil bestemme hvilke rettigheder De har i app'en, samt hvilke sider De kan tilgå.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Role')),
                ('team', models.ForeignKey(blank=True, default=None, help_text='Arbejdsholdet brugeren skal tilkobles.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='teams.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
