# Generated by Django 3.0.7 on 2020-06-30 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, default=None, help_text="Brugerens rolle. Denne vil bestemme hvilke rettigheder de har i app'en, samt hvilke sider de kan tilgå.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Role'),
        ),
    ]
