# Generated by Django 3.0.6 on 2020-05-29 08:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Et telefonnummer du kan kontaktes på.', max_length=8, validators=[django.core.validators.RegexValidator('[0-9]*', 'Dit telefonnummer kan kun indeholde tal.')])),
                ('pfp', models.ImageField(default='img/default.jpg', upload_to='img/pfp/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.OneToOneField(blank=True, default=None, help_text="Brugerens rolle. Denne vil bestemme hvilke rettigheder De har i app'en, samt hvilke sider De kan tilgå.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Role')),
                ('team', models.OneToOneField(blank=True, default=None, help_text='Arbejdsholdet brugeren skal tilkobles.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='teams.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
