# Generated by Django 3.0.6 on 2020-06-02 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Et telefonnummer du kan kontaktes på.', max_length=8, null=True, validators=[django.core.validators.RegexValidator('[0-9]*', 'Dit telefonnummer kan kun indeholde tal.')]),
        ),
    ]
