# Generated by Django 3.0.6 on 2020-06-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200602_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='display_name',
            field=models.CharField(default=0, error_messages={'required': 'Visningsnavnefeltet er påkrævet.'}, help_text='Navnet der bliver vist på siden.', max_length=255),
            preserve_default=False,
        ),
    ]
