# Generated by Django 3.0.6 on 2020-06-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, default=None, help_text="Brugerens rolle. Denne vil bestemme hvilke rettigheder De har i app'en, samt hvilke sider De kan tilgå.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Role'),
        ),
    ]
