# Generated by Django 3.0.7 on 2020-06-12 06:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20200612_0650'),
        ('users', '0005_auto_20200604_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default=None, help_text='Et telefonnummer du kan kontaktes på.', max_length=8, null=True, validators=[django.core.validators.RegexValidator('[0-9]*', 'Dit telefonnummer kan kun indeholde tal.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(blank=True, default=None, help_text='Arbejdsholdet brugeren skal tilkobles.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(error_messages={'required': 'Navnefeltet er påkrævet.'}, help_text='Et beskrivende navn til rollen.', max_length=255, unique=True),
        ),
    ]
