# Generated by Django 3.0.6 on 2020-06-02 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Navnefeltet er påkrævet.'}, help_text='Navnet på dit projekt.', max_length=255)),
                ('description', models.TextField(error_messages={'required': 'Beskrivelsesfeltet er påkrævet'}, help_text='En klar og detaljeret beskrivelse af projektet.')),
                ('slug', models.SlugField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Modtaget'), ('CURRENT', 'Igangværende'), ('DONE', 'Færdig')], default='PENDING', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='leader', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('team', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='teams.Team')),
            ],
        ),
    ]
