# Generated by Django 3.0.7 on 2020-06-18 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'required': 'Titel feltet er påkrævet.'}, max_length=255)),
                ('description', models.CharField(error_messages={'required': 'Beskrivelsesfeltet er påkrævet.'}, max_length=255)),
                ('img', models.ImageField(upload_to=projects.models.get_upload_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'required': 'Titel feltet er påkrævet.'}, max_length=255)),
                ('description', models.CharField(error_messages={'required': 'Beskrivelsesfeltet er påkrævet.'}, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Navnefeltet er påkrævet.'}, help_text='Navnet på dit projekt.', max_length=255)),
                ('description', models.TextField(error_messages={'required': 'Beskrivelsesfeltet er påkrævet'}, help_text='En klar og detaljeret beskrivelse af projektet.')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Modtaget'), ('CURRENT', 'Igangværende'), ('DONE', 'Færdig')], default='PENDING', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='leader', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
