# Generated by Django 3.0.6 on 2020-06-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
    ]
