# Generated by Django 3.0.6 on 2020-06-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_projects'),
        ('projects', '0006_auto_20200604_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, default=None, help_text='Holdet i firmaet, som du ønsker skal tage imod dit projekt.<br>Hvis du ikke vælger et, kan ethvert hold tage imod det.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='teams.Team'),
        ),
    ]
