# Generated by Django 3.0.7 on 2020-06-09 07:17

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200608_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='img',
            field=models.ImageField(upload_to=projects.models.get_upload_path),
        ),
    ]
