# Generated by Django 3.0.6 on 2020-05-29 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'Navnefeltet er påkrævet.'}, help_text='Et beskrivende navn til dit hold.', max_length=255)),
                ('description', models.CharField(error_messages={'required': 'Beskrivelsesfeltet er påkrævet.'}, help_text='En lille beskrivelse af dit holds funktion.', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
