# Generated by Django 3.0.6 on 2020-06-04 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_team'),
        ('teams', '0002_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='projects',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
