# Generated by Django 3.0.6 on 2020-06-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='projects',
        ),
    ]
