# Generated by Django 3.0.7 on 2020-06-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(error_messages={'required': 'Navnefeltet er påkrævet.'}, help_text='Et beskrivende navn til dit hold.', max_length=255, unique=True),
        ),
    ]
