# Generated by Django 3.0.7 on 2020-06-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(error_messages={'required': 'Navnefeltet er påkrævet.'}, help_text='Et beskrivende navn til dit hold. Dette er navnet kunder og kollegaer vil se, når de vil oprette et projekt til dig.', max_length=255, unique=True),
        ),
    ]
